### ISSUE TITLE
Fix the image and header sizing on the apply panel

### ISSUE THREAD

**Issue by ghost** [hack4impact/hack4impact-website#10]
## To reproduce

Head to `/apply/nonprofit` (for example). Notice how the header, button, and image differ from the mockup below.

## Author notes

- Image and text should be split 50% / 50% on the `tablet` breakpoint and above (check `variables.scss`). Below this, wrap the image to the line below.
- The button shouldn't be stretched

<img width="798" alt="image" src="https://user-images.githubusercontent.com/31811199/94092352-82633080-fde8-11ea-9c5c-c57aa8e969cd.png">

**Comment by DeveloperKhan** [comment]
Yeet, I pushed to main directly, yeet
